### ISSUE TITLE
História de Usuário: Instalação da Versão demo do Machado Genomics e documentação

### ISSUE THREAD

**Issue by LucassSantoss** [gcontiero11/machado#19]
Derivado do card #11 
- Definição: Como um desenvolvedor do projeto, eu quero instalar a versão demo do Machado Genomics e realizar testes com amostras de dados genômicos, para que eu possa garantir que a integração e o carregamento de dados funcionam corretamente antes do desenvolvimento.

- Critérios de Aceitação
- [x] Instalação da Versão Demo
- [x] O ambiente deve ser capaz de simular as condições reais de operação
- [x] A instalação deve seguir a documentação oficial do Machado Genomics
- [x] Quaisquer problemas encontrados durante a instalação ou os testes devem ser registrados
- [x] Um relatório final deve ser criado, contendo os resultados obtidos

**Comment by brunomascioli** [comment]
Segue o relatório abaixo:
[Relatório de Instalação - Machado .pdf](https://github.com/user-attachments/files/16969606/Relatorio.de.Instalacao.-.Machado.pdf)
